#!/bin/bash

# Command to call openscad
OPENSCAD=openscad-nightly

# loop over all .dxf.scad or .stl.scad files in build build directory
for source in build/*.stl.scad ; do
  dest=`basename --suffix=.scad ${source}`

  echo "Building artifacts/${dest} from ${source}"
  ${OPENSCAD} --imgsize=1920,1200 -o renders/${dest} ${source}
done


